-- Roblox Appeals Table
-- This table stores Roblox appeal submissions, mirroring the structure for Discord appeals.

CREATE TABLE public.roblox_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roblox_id TEXT NOT NULL,
    roblox_username TEXT NOT NULL,
    appeal_text TEXT NOT NULL,
    ban_data JSONB, -- To store ban history or live status
    short_ban_reason TEXT,
    status TEXT DEFAULT 'pending', -- e.g., pending, approved, rejected
    moderator_id TEXT,
    moderator_username TEXT,
    moderator_action_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for faster lookups
CREATE INDEX idx_roblox_appeals_roblox_id ON public.roblox_appeals(roblox_id);
CREATE INDEX idx_roblox_appeals_status ON public.roblox_appeals(status);

-- Comments on columns
COMMENT ON COLUMN public.roblox_appeals.id IS 'Unique identifier for the appeal.';
COMMENT ON COLUMN public.roblox_appeals.roblox_id IS 'The Roblox user ID of the appellant.';
COMMENT ON COLUMN public.roblox_appeals.roblox_username IS 'The Roblox username of the appellant at the time of appeal.';
COMMENT ON COLUMN public.roblox_appeals.appeal_text IS 'The user-submitted text for their appeal.';
COMMENT ON COLUMN public.roblox_appeals.ban_data IS 'JSONB blob containing ban history and live ban status from the Roblox API.';
COMMENT ON COLUMN public.roblox_appeals.short_ban_reason IS 'The shortened, categorized ban reason.';
COMMENT ON COLUMN public.roblox_appeals.status IS 'The current status of the appeal (e.g., pending, approved, rejected).';
COMMENT ON COLUMN public.roblox_appeals.moderator_id IS 'The Discord user ID of the moderator who handled the appeal.';
COMMENT ON COLUMN public.roblox_appeals.moderator_username IS 'The Discord username of the moderator.';
COMMENT ON COLUMN public.roblox_appeals.moderator_action_at IS 'Timestamp when a moderator took action.';
COMMENT ON COLUMN public.roblox_appeals.created_at IS 'Timestamp when the appeal was submitted.';
COMMENT ON COLUMN public.roblox_appeals.updated_at IS 'Timestamp when the appeal was last updated.';
